# Generated by Django 5.0.6 on 2024-06-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('protein', models.IntegerField()),
                ('creatine', models.IntegerField()),
                ('bcaa', models.IntegerField()),
            ],
        ),
    ]
